---
title: "Overview table of functions"
author: "DARTH"
date: "19-2-2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Table 

|   **Function of the files**                                                  |
|:-----------------------------------------------------------------------------|
| 01_model-inputs_function.R                                                   |
| - `f.define_init_params()`                                                   |
|* argument: none                                                              |
|* returns: `df.params.init`                                                   |
| This function creates a dataframe with the base-case parameters of the model, called `df.params.init`. The function does not require any arguments. External data from a csv file is loaded into the environment and the parameters that need to be calibrated get an placeholder value to make it possible to run the model. These values will be replaced after the calibrated values are known. The dataframe `df.params.init` including all base-case parameters values  is returned.     |
|                                                                              | 
| 02_simulation-model_function.R                                               |
| - `f.decision_model()`                                              |
| * argument: `df.params`                                                      |
| * returns: `a.P` and `m.M`                                                   |
| The input for this function is the `df.params` dataframe including all base-case parameter values generated by the `f.define_init_params()`. Based on this dataframe the age-specific transition probabilities are calculated for all cycles. The second step is the initation of the age-specific transition probability matrices in an array, called `a.P`. The functions incluces two checks to make sure that each transition probability is a valid value as well as the transition probability matrix as a whole. The third part of the model initiate the cohort trace `m.M` that will be used to store the model results that are generated by iterating the STM over time. |
|                                                                              |
| 03_calibratioin_function.R                                                   |
| - `f.calibration_out()`                                        |
| * argument: `v.params.calib`                                                 |
| * returns: `l.out`                                                           |
| The function `f.calibration_out` the values of the uncalibrated parameters in the base-case dataframe are substituted by values of calibrated parameters in the vector `v.params.calib`. The function `f.decision_model(df.params)` is used again to run the model with the new values for the calibrated parameters. Based on the new model results the epidemiological measures, 
overal survival, disease prevalence and the proportion of sick in the sick states is estimated. At three timepoints, `t = 11`, `t = 21` and `t = 31`, the values of all three the epidemiological measuread are stored in the list `l.out`. This list is the output of the function.                                                                      |
| - `f.log_lik()`
| * argument: `v.params`                                                       |
| * returns: `v.llik.overall`                                                  |
| DESCRIPTION  | 
| - `likelihood(v.params)`
| * argument: `v.params`                                                       |
| * returns:                                                                   |
| DESCRIPTION  |
| - `sample.prior()`                                                     |
| * argument: `n.samp`                                                         |
| * returns: `m.param.samp`                                                    |
| DESCRIPTION  |
| `f.log_prior`
| * argument: `v.params`                                                       |
| * returns:                                                                   |
| DESCRIPTION  |
| `prior`
| * argument: `v.params`                                                       |
| * returns:                                                                   |
| DESCRIPTION  |
| `f.log_post`
| * argument: `v.params`                                                       |
| * returns: `n.lpost`                                                                  |
| DESCRIPTION  |


