################################################################################ 
# This script runs the cost-effectiveness analysis of a hypothetical treatment #
# for the simulated cohort of the Sick-Sicker state-transition model (STM)     #
#                                                                              # 
# Depends on:                                                                  #
#   01_model-inputs.R                                                          #
#   02_simulation-model_functions.R                                            #
#                                                                              # 
# Author: Fernando Alarid-Escudero                                             # 
# E-mail: fernando.alarid@cide.edu                                             # 
################################################################################ 
# The structure of this code is generated by the DARTH workgroup               #
# https://github.com/DARTH-git/Decision-Modeling-Framework                     #
################################################################################ 
# rm(list = ls()) # to clean the workspace

#### 04.1 Load packages and functions ####
#### 04.1.1 Load packages ####
# PSA functionality
library(truncnorm) # truncated normal distribution

#### 03.1.2 Load inputs ####
source("R/01_model-inputs.R")

#### 04.1.3 Load functions ####
source("functions/02_simulation-model_functions.R")
source("functions/04_cost-effectiveness-analysis_functions.R")

#### 04.2 Cost-effectiveness analysis parameters ####
## Strategy names
v.names.str <- c("No Treatment", "Treatment")  
## Number of strategies
n.str <- length(v.names.str)
v.params.basecase <- f.generate_basecase_params()

#### 04.3 Compute cost-effectiveness outcomes ####
f.calculate_ce_out(v.params.basecase)

#### 04.4 Conduct cost-effectiveness analysis ####
# m.cea <- calculate_icers(m.ce)

#### 04.5 Plot cost-effectiveness frontier ####
# l.cea.frontier <- getFrontier(m.ce)
# gg.cea.frontier <- plot(l.cea.frontier)

#### 04.6 Deterministic sensitivity analysis (DSA) ####
#### 04.6.1 One-way sensitivity analysis (OWSA) ####
#### 04.6.2 Two-way sensitivity analysis (TWSA) ####

#### 04.7 Probabilistic sensitivity analysis (PSA) ####
